server:
  port: ${PORT:8081}

spring:
  application:
    name: auth-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Merged Cloud Configuration
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:noop}
        secret-key: ${AWS_SECRET_KEY:noop}
      region:
        static: ${AWS_REGION:us-east-1}
      s3:
        enabled: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  # AWS Config for your CUSTOM CODE (if using @Value("${cloud.aws.s3.bucket-name}"))
cloud:
  aws:
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME:local-bucket}
      folder-name: ${AWS_S3_FOLDER_NAME:uploads}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:3600000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans

springdoc:
  swagger-ui:
    enabled: true

url:
  front-end: ${FRONT_END:http://localhost:3000}

socketio:
  host: 0.0.0.0
  port: ${SOCKET_IO_PORT:9095}
  origin: ${url.front-end}

codes:
  admin: ${CODE_ADMIN:admin123}
  especialista: ${CODE_EXPERT:expert123}

google:
  client-id: ${GOOGLE_CLIENT_ID:your-google-id}

telegram:
  bot:
    username: ${TELEGRAM_CHAT_ID}
    token: ${TELEGRAM_BOT_TOKEN:8235446930:AAGBIXQ2v-6z4fhVGmiY-gOPh1s6ZokXTg4}